import { Platform, StyleSheet } from 'react-native';
import { brand } from '../data/mockData';

export const nowTime = () =>
  new Date().toLocaleTimeString([], {
    hour: 'numeric',
    minute: '2-digit',
  });

export const shadow = Platform.select({
  ios: {
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  android: {
    elevation: 3,
  },
  default: {
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
});

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: brand.secondary,
  },
  splashSafeArea: {
    flex: 1,
    backgroundColor: brand.primary,
  },
  splashContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashRippleOne: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.09)',
  },
  splashRippleTwo: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  splashRippleThree: {
    position: 'absolute',
    width: 380,
    height: 380,
    borderRadius: 190,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  logoTile: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  logoLetter: {
    fontSize: 34,
    fontWeight: '800',
    color: brand.primary,
  },
  splashBrand: {
    color: '#fff',
    fontSize: 34,
    fontWeight: '800',
  },
  splashTagline: {
    color: 'rgba(255,255,255,0.82)',
    marginTop: 8,
    fontSize: 15,
  },
  lightScreen: {
    flex: 1,
    backgroundColor: brand.secondary,
  },
  darkScreen: {
    flex: 1,
    backgroundColor: '#0A0B13',
  },
  flexFill: {
    flex: 1,
  },
  onboardingHero: {
    height: '58%',
    justifyContent: 'space-between',
  },
  coverImage: {
    resizeMode: 'cover',
  },
  onboardingTopRow: {
    alignItems: 'flex-end',
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  skipPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(44,44,44,0.28)',
  },
  skipText: {
    color: '#fff',
    fontWeight: '700',
  },
  onboardingFade: {
    height: 180,
  },
  onboardingBody: {
    paddingHorizontal: 22,
    paddingTop: 8,
    gap: 12,
  },
  dotRow: {
    flexDirection: 'row',
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D7D1C8',
  },
  dotActive: {
    width: 22,
    backgroundColor: brand.primary,
  },
  heroTitle: {
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '800',
    color: brand.text,
  },
  heroText: {
    fontSize: 16,
    lineHeight: 25,
    color: brand.muted,
  },
  bottomButtonWrap: {
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  welcomeHero: {
    flex: 1,
  },
  welcomeHeroImage: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  welcomeOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 24,
  },
  welcomeTitle: {
    color: '#fff',
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '800',
    marginBottom: 12,
  },
  welcomeText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 320,
  },
  authActions: {
    paddingHorizontal: 22,
    paddingTop: 22,
    gap: 14,
  },
  termsText: {
    paddingHorizontal: 22,
    paddingVertical: 18,
    textAlign: 'center',
    color: brand.muted,
    fontSize: 12,
  },
  primaryButton: {
    backgroundColor: brand.primary,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  outlineButton: {
    borderWidth: 1.5,
    borderColor: brand.primary,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  outlineButtonText: {
    color: brand.primary,
    fontSize: 16,
    fontWeight: '800',
  },
  formScreen: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 36,
    gap: 14,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECE7E0',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: brand.text,
  },
  sectionHeadline: {
    fontSize: 34,
    fontWeight: '800',
    color: brand.text,
    marginTop: 4,
  },
  sectionSubline: {
    color: brand.muted,
    fontSize: 15,
    marginBottom: 6,
  },
  segmentedRow: {
    flexDirection: 'row',
    backgroundColor: '#EAE5DE',
    borderRadius: 16,
    padding: 4,
    marginBottom: 4,
  },
  segment: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: brand.primary,
  },
  segmentText: {
    color: brand.muted,
    fontWeight: '700',
  },
  segmentTextActive: {
    color: '#fff',
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: brand.text,
  },
  input: {
    backgroundColor: '#ECE7E0',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 15,
    color: brand.text,
  },
  inputMultiline: {
    minHeight: 116,
    textAlignVertical: 'top',
  },
  helperCenterText: {
    color: brand.muted,
    textAlign: 'center',
    fontSize: 14,
    marginTop: 6,
  },
  helperLink: {
    color: brand.primary,
    fontWeight: '800',
  },
  mainShell: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 24,
    gap: 18,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  mutedCopy: {
    color: brand.muted,
    fontSize: 14,
  },
  mutedCopySmall: {
    color: brand.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  titleLarge: {
    fontSize: 34,
    fontWeight: '800',
    color: brand.text,
  },
  topActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECE7E0',
  },
  iconButtonFilled: {
    backgroundColor: brand.primary,
  },
  iconBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: brand.danger,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  iconBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ECE7E0',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    ...shadow,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: brand.primary,
  },
  statLabel: {
    color: brand.muted,
    fontSize: 12,
    marginTop: 4,
  },
  liveCard: {
    backgroundColor: brand.primary,
    borderRadius: 22,
    padding: 18,
    gap: 10,
    ...shadow,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF655E',
  },
  liveBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  liveTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
  },
  liveMeta: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
  },
  inlineButton: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  inlineButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: brand.text,
  },
  sectionLink: {
    fontSize: 13,
    color: brand.primary,
    fontWeight: '800',
  },
  horizontalList: {
    gap: 12,
  },
  sessionCard: {
    width: 220,
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: brand.border,
    ...shadow,
  },
  sessionTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
    color: brand.text,
  },
  sessionTime: {
    color: brand.muted,
    fontSize: 13,
  },
  sessionParticipants: {
    color: brand.muted,
    fontSize: 12,
  },
  communityRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: brand.border,
  },
  communityThumb: {
    width: 54,
    height: 54,
    borderRadius: 14,
  },
  communityName: {
    fontSize: 16,
    fontWeight: '800',
    color: brand.text,
  },
  screenHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  screenTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: brand.text,
    flex: 1,
  },
  searchBar: {
    backgroundColor: '#ECE7E0',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchPlaceholder: {
    color: brand.muted,
    fontSize: 14,
  },
  filterPillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: '#E8E4DE',
    alignSelf: 'flex-start',
  },
  pillActive: {
    backgroundColor: brand.primary,
  },
  pillText: {
    fontSize: 12,
    fontWeight: '700',
    color: brand.muted,
  },
  pillTextActive: {
    color: '#fff',
  },
  pillCompact: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  recommendedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#E8E6F6',
    borderRadius: 18,
    padding: 14,
  },
  recommendedIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#D8D3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recommendedTitle: {
    color: brand.primary,
    fontWeight: '800',
    fontSize: 14,
  },
  largeCommunityCard: {
    overflow: 'hidden',
    borderRadius: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: brand.border,
  },
  largeCommunityImage: {
    width: '100%',
    height: 126,
  },
  cardBody: {
    padding: 14,
    gap: 10,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  communityDescription: {
    color: brand.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  liveHeroCard: {
    backgroundColor: brand.primary,
    borderRadius: 22,
    padding: 18,
    gap: 8,
  },
  liveHeroLabel: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  liveHeroTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
  },
  liveHeroMeta: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  primarySmallButton: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 12,
    borderRadius: 16,
    alignItems: 'center',
  },
  primarySmallText: {
    color: brand.primary,
    fontWeight: '800',
  },
  ghostSmallButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D4D4FF',
    paddingVertical: 12,
    borderRadius: 16,
    alignItems: 'center',
  },
  ghostSmallText: {
    color: '#fff',
    fontWeight: '800',
  },
  filterSummaryCard: {
    borderRadius: 18,
    backgroundColor: '#fff',
    padding: 16,
    borderWidth: 1,
    borderColor: brand.border,
  },
  filterSummaryTitle: {
    color: brand.text,
    fontWeight: '800',
    marginBottom: 8,
  },
  filterSummaryText: {
    color: brand.muted,
    lineHeight: 20,
  },
  sessionListCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: brand.border,
    gap: 8,
  },
  sessionListTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  threadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ECE7E0',
  },
  threadTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  threadName: {
    fontSize: 15,
    fontWeight: '800',
    color: brand.text,
  },
  threadTime: {
    color: brand.muted,
    fontSize: 12,
  },
  threadPreview: {
    color: brand.muted,
    fontSize: 13,
    marginTop: 4,
  },
  unreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#D46937',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  unreadText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 11,
  },
  profileScrollContent: {
    paddingBottom: 28,
  },
  profileHero: {
    height: 160,
    backgroundColor: brand.primary,
  },
  floatingEditButton: {
    position: 'absolute',
    right: 20,
    top: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCard: {
    marginTop: -34,
    backgroundColor: brand.secondary,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 16,
  },
  profileTopRow: {
    width: 74,
    height: 74,
  },
  profileAvatar: {
    width: 74,
    height: 74,
    borderRadius: 37,
    borderWidth: 3,
    borderColor: '#fff',
  },
  onlineDot: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#59B980',
    borderWidth: 2,
    borderColor: '#fff',
  },
  profileHeadingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF8E7',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#B16A0E',
  },
  profileBio: {
    color: brand.text,
    fontSize: 14,
    lineHeight: 22,
  },
  subsectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: brand.text,
    marginTop: 6,
  },
  skillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  badgesRow: {
    flexDirection: 'row',
    gap: 12,
  },
  badgeCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: brand.border,
    gap: 4,
  },
  badgeEmoji: {
    fontSize: 22,
  },
  badgeLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: brand.text,
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#FDF2F1',
    marginTop: 8,
  },
  signOutText: {
    color: brand.danger,
    fontWeight: '800',
    fontSize: 15,
  },
  profileName: {
    fontSize: 26,
    fontWeight: '800',
    color: brand.text,
  },
  profileMajor: {
    color: brand.muted,
    fontSize: 14,
    marginTop: 2,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
  },
  actionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#ECE7E0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: brand.text,
  },
  circleIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleIconFilled: {
    backgroundColor: brand.primary,
  },
  circleIconLight: {
    backgroundColor: '#ECE7E0',
  },
  fieldShell: {
    gap: 6,
  },
  filterSection: {
    gap: 10,
    marginBottom: 8,
  },
  filterTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: brand.text,
  },
  filterWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
    backgroundColor: '#ECE7E0',
  },
  filterChipActive: {
    backgroundColor: brand.primary,
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: brand.muted,
  },
  filterChipTextActive: {
    color: '#fff',
  },
  communityDetailContent: {
    paddingBottom: 80,
  },
  communityHero: {
    height: 200,
    justifyContent: 'flex-end',
  },
  communityHeroOverlay: {
    padding: 18,
    gap: 4,
  },
  communityHeroActions: {
    position: 'absolute',
    top: 14,
    left: 14,
    right: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  communityHeroTitle: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
  },
  communityHeroMeta: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
  },
  communityTabRow: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
    backgroundColor: '#fff',
  },
  communityTabText: {
    fontSize: 14,
    fontWeight: '700',
    color: brand.muted,
  },
  communityTabTextActive: {
    color: brand.primary,
    borderBottomWidth: 2,
    borderBottomColor: brand.primary,
  },
  sharePrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    marginHorizontal: 20,
    marginTop: 14,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: brand.border,
  },
  shareAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: brand.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareAvatarText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  postCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginHorizontal: 20,
    marginTop: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: brand.border,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  postTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: brand.text,
  },
  postBody: {
    color: brand.text,
    fontSize: 14,
    lineHeight: 20,
  },
  stickyBottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderTopWidth: 1,
    borderTopColor: brand.border,
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
    backgroundColor: '#fff',
  },
  onlineText: {
    color: '#59B980',
    fontSize: 12,
    fontWeight: '700',
  },
  chatMessages: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
  },
  chatDayMarker: {
    textAlign: 'center',
    color: brand.muted,
    fontSize: 12,
    marginVertical: 8,
  },
  messageBubble: {
    maxWidth: '78%',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  messageBubbleMine: {
    alignSelf: 'flex-end',
    backgroundColor: brand.primary,
  },
  messageBubbleTheirs: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: brand.border,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    color: brand.text,
  },
  messageTextMine: {
    color: '#fff',
  },
  messageTime: {
    fontSize: 11,
    color: brand.muted,
    alignSelf: 'flex-end',
  },
  messageTimeMine: {
    color: 'rgba(255,255,255,0.7)',
  },
  chatComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: brand.border,
    backgroundColor: brand.secondary,
  },
  composerInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: brand.text,
  },
  sessionLobbyBg: {
    flex: 1,
  },
  sessionLobbyAttendees: {
    alignItems: 'flex-end',
    gap: 10,
    paddingTop: 20,
    paddingRight: 16,
  },
  lobbyAvatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  sessionLobbyCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
    gap: 14,
  },
  liveBadgeOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(122,34,34,0.28)',
  },
  lobbyTitle: {
    color: '#fff',
    fontSize: 34,
    lineHeight: 40,
    textAlign: 'center',
    fontWeight: '800',
  },
  lobbyMeta: {
    color: 'rgba(255,255,255,0.78)',
  },
  sessionControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingBottom: 28,
  },
  controlItem: {
    alignItems: 'center',
    gap: 8,
  },
  controlCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaveCircle: {
    backgroundColor: '#D8473C',
  },
  controlText: {
    color: '#fff',
    fontSize: 12,
  },
  saveChip: {
    backgroundColor: brand.primary,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
  },
  saveChipText: {
    color: '#fff',
    fontWeight: '800',
  },
  editAvatarWrap: {
    alignItems: 'center',
    marginBottom: 8,
  },
  editAvatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
  },
  editAvatarBadge: {
    position: 'absolute',
    right: '35%',
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: brand.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: brand.secondary,
  },
  settingsSectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: brand.muted,
    marginTop: 8,
    marginBottom: 6,
  },
  settingsCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: brand.border,
  },
  preferenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  preferenceRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
  },
  preferenceLabel: {
    color: brand.text,
    fontWeight: '800',
    marginBottom: 4,
  },
  textAvatar: {
    backgroundColor: '#D67234',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textAvatarLabel: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: brand.border,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  tabItem: {
    alignItems: 'center',
    gap: 4,
    minWidth: 62,
  },
  tabLabel: {
    fontSize: 11,
    color: brand.muted,
  },
  tabLabelActive: {
    color: brand.primary,
    fontWeight: '800',
  },
  controlCircleActive: {
    backgroundColor: brand.primary,
  },
  controlCircleHand: {
    backgroundColor: '#E07038',
  },
  cameraPreviewWrap: {
    width: 130,
    height: 175,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#fff',
    position: 'absolute',
    bottom: 100,
    right: 16,
    zIndex: 10,
  },
  cameraPreviewImage: {
    width: '100%',
    height: '100%',
  },
  cameraOffOverlay: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1E202C',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  cameraOffText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
  },
  handRaisedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#E07038',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
  },
  handRaisedText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '75%',
    gap: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: brand.border,
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: brand.text,
  },
  participantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EEEA',
  },
  participantRole: {
    color: brand.muted,
    fontSize: 12,
  },
  videoModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  videoPlayerCard: {
    backgroundColor: '#13141E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '90%',
    gap: 14,
  },
  videoPlayerScreen: {
    width: '100%',
    height: 210,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  videoPlayOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  videoProgressBarWrap: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  videoProgressBarFill: {
    height: '100%',
    backgroundColor: brand.primary,
  },
  videoControlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 6,
  },
  speedPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  speedPillActive: {
    backgroundColor: brand.primary,
  },
  speedPillText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
    fontWeight: '700',
  },
  speedPillTextActive: {
    color: '#fff',
  },
  chapterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  chapterTimeText: {
    color: '#E07038',
    fontSize: 12,
    fontWeight: '800',
  },
  levelProgressTrack: {
    height: 8,
    backgroundColor: '#E2DFD7',
    borderRadius: 4,
    overflow: 'hidden',
    marginVertical: 6,
  },
  levelProgressFill: {
    height: '100%',
    backgroundColor: '#E07038',
  },
  levelBadgeChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#FFF0D6',
    alignSelf: 'flex-start',
  },
  levelBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#B16A0E',
  },
  perkCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brand.border,
    marginBottom: 10,
  },
  perkIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#FFF4EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perkCostBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: '#E6F4EA',
  },
  perkCostText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#137333',
  },
  voucherCodeBox: {
    backgroundColor: '#F4F2EE',
    padding: 14,
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    borderColor: brand.primary,
    alignItems: 'center',
    marginVertical: 10,
  },
  voucherCodeText: {
    fontSize: 20,
    fontWeight: '800',
    color: brand.primary,
    letterSpacing: 2,
  },
  mapPreviewBox: {
    width: '100%',
    height: 180,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#E2DFD7',
    marginVertical: 10,
  },
  mapPinMarker: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: brand.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  directionsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    backgroundColor: '#EFF6FF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  directionsText: {
    color: '#1E40AF',
    fontSize: 13,
    fontWeight: '700',
  },
  hotspotWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginVertical: 6,
  },
  hotspotChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#ECE7E0',
  },
  hotspotChipActive: {
    backgroundColor: brand.primary,
  },
  hotspotChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: brand.muted,
  },
  hotspotChipTextActive: {
    color: '#fff',
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#E6F4EA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  verifiedText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#137333',
  },
  endorseChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: brand.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  endorseCount: {
    fontSize: 11,
    fontWeight: '800',
    color: brand.primary,
  },
  reviewCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: brand.border,
    gap: 6,
    marginBottom: 8,
  },
  starRow: {
    flexDirection: 'row',
    gap: 6,
    marginVertical: 6,
  },
  globalSearchBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-start',
    paddingTop: 50,
  },
  globalSearchCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    borderRadius: 22,
    padding: 18,
    maxHeight: '85%',
    gap: 12,
  },
  globalSearchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECE7E0',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  globalSearchInput: {
    flex: 1,
    fontSize: 15,
    color: brand.text,
    fontWeight: '600',
  },
  entityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: '#E0E7FF',
    alignSelf: 'flex-start',
  },
  entityBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: brand.primary,
  },
  searchResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F2EE',
  },
  resourceFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brand.border,
    marginBottom: 10,
  },
  pdfIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  downloadPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: brand.primary,
  },
  downloadPillDone: {
    backgroundColor: '#E6F4EA',
  },
  fileSizeText: {
    fontSize: 11,
    color: brand.muted,
    marginTop: 2,
  },
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F2EE',
  },
  notificationUnreadRow: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 10,
    borderRadius: 14,
    borderBottomWidth: 0,
    marginBottom: 6,
  },
  notificationIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#E0E7FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: brand.primary,
  },
  streakCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: brand.border,
    marginVertical: 10,
    gap: 10,
  },
  streakDaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  streakDayItem: {
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: '#F4F2EE',
    minWidth: 40,
  },
  streakDayItemActive: {
    backgroundColor: '#FFF4EB',
    borderWidth: 1,
    borderColor: '#FFE4D1',
  },
  streakDayName: {
    fontSize: 11,
    fontWeight: '700',
    color: brand.muted,
  },
  goalTaskCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: brand.border,
    marginBottom: 8,
  },
  goalTaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
});
