/**
 * Profile, editing, password and notification preferences.
 */
import { StyleSheet } from 'react-native';
import { brand } from '@/data/mockData';
import { shadowSm, space } from '../tokens';
import type { ThemeColors } from '../theme';

export const profileStyles = (c: ThemeColors) =>
  StyleSheet.create({
    profileScrollContent: {
      paddingBottom: 28,
    },
    profileHero: {
      height: 160,
      backgroundColor: brand.primary,
    },
    floatingEditButton: {
      position: 'absolute',
      right: 20,
      top: 20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.22)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileCard: {
      marginTop: -34,
      backgroundColor: c.bg,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 20,
      gap: 16,
      ...shadowSm,
    },
    profileTopRow: {
      width: 74,
      height: 74,
    },
    profileAvatar: {
      width: 74,
      height: 74,
      borderRadius: 37,
      borderWidth: 3,
      borderColor: '#fff',
    },
    onlineDot: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: '#59B980',
      borderWidth: 2,
      borderColor: '#fff',
    },
    profileHeadingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    ratingPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#FFF8E7',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
    },
    ratingText: {
      fontSize: 12,
      fontWeight: '800',
      color: '#B16A0E',
    },
    profileBio: {
      color: c.text,
      fontSize: 14,
      lineHeight: 22,
    },
    subsectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: c.text,
      marginTop: 6,
    },
    signOutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
      borderRadius: 16,
      backgroundColor: '#FDF2F1',
      marginTop: 8,
    },
    signOutText: {
      color: brand.danger,
      fontWeight: '800',
      fontSize: 15,
    },
    profileName: {
      fontSize: 26,
      fontWeight: '800',
      color: c.text,
    },
    saveChip: {
      backgroundColor: brand.primary,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 999,
    },
    saveChipText: {
      color: '#fff',
      fontWeight: '800',
    },
    editAvatarWrap: {
      alignItems: 'center',
      marginBottom: 8,
    },
    editAvatar: {
      width: 86,
      height: 86,
      borderRadius: 43,
    },
    editAvatarBadge: {
      position: 'absolute',
      right: '35%',
      bottom: 0,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: brand.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: brand.secondary,
    },
    settingsCard: {
      backgroundColor: c.card,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: c.border,
    },
    preferenceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    preferenceRowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: brand.border,
    },
    preferenceLabel: {
      color: c.text,
      fontWeight: '800',
      marginBottom: 4,
    },
    verifiedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: '#E6F4EA',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      alignSelf: 'flex-start',
      marginTop: 4,
    },
    verifiedText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#137333',
    },
    endorseChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
    },
    endorseCount: {
      fontSize: 11,
      fontWeight: '800',
      color: brand.primary,
    },
    reviewCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 14,
      borderWidth: 1,
      borderColor: c.border,
      gap: 6,
      marginBottom: 8,
    },
  });
